name: Physics Server Box2D Upload
description: Upload Godot Cpp and the Physics Server 2D Extension.

runs:
  using: composite
  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Godot Box2D
        path: |
          ${{ github.workspace }}/bin/**
        retention-days: 14
