name: Physics Server Box2D Upload
description: Upload Godot Cpp and the Physics Server 2D Extension.

inputs:
  platform:
    required: true
    description: Target platform.
  arch:
    required: true
    description: Target architecture.

runs:
  using: composite
  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: godot-box2d-${{ inputs.platform }}-${{ inputs.arch }}
        path: |
          ${{ github.workspace }}/bin/**
        retention-days: 14
