name: Release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.3.0
        id: version
        with:
          bump_each_commit: true
          tag_prefix: "v"
          debug: true
      - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: godot-box2d-*
        merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts
      - name: Delete draft release(s)
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        shell: sh
        run: |
          mkdir -p godot-box2d
          cp -r artifacts/* godot-box2d/
          zip -r "godot-box2d.v${{steps.version.outputs.version}}.zip" godot-box2d
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Godot Box2D ${{ steps.version.outputs.version }}
          files: godot-box2d.v${{ steps.version.outputs.version }}.zip
          generate_release_notes: true
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
