name: 🌐 Web Builds
on:
  workflow_call:

# Global Settings
env:
  EM_VERSION: 3.1.39
  EM_CACHE_FOLDER: "emsdk-cache"
  EM_CACHE_KEY: "emscripten-${{ github.run_id }}"

jobs:
  web:
    runs-on: ubuntu-latest
    name: Web Build ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [wasm32]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Build ${{ matrix.arch }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: web

      - name: Upload ${{ matrix.arch }}
        uses: ./.github/actions/upload
        with:
          arch: ${{ matrix.arch }}
          platform: web
    
